<footer class="page-footer white"> 
	<a href="index.php">Return to Main Page</a>
	<br>
	<a href="colophon.php">About This Website</a>

	<ul class="pagination">
	    <li class="diabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
	    <li class="waves-effect"><a href="index.php">1</a></li>
	    <li class="waves-effect"><a href="tim-berners-lee.php">2</a></li>
	    <li class="waves-effect"><a href="grace-hopper.php">3</a></li>
	    <li class="waves-effect"><a href="margaret-hamilton.php">4</a></li>
	    <li class="waves-effect"><a href="colophon.php">5</a></li>
	    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
  </ul>	
			
</footer>

