<head>
	<meta charset="utf-8">
	
	<title>People in Computing</title> 
	
	
	<!--CND import of Materialize JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

	<!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/> <!--required for Materialize framework-->
    <link rel="stylesheet" href="css/override.css">

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">

	<script src="js/menuhighlight.js"></script>


</head>