<nav class="nav blue darken-3">
	<div class="nav-wrapper">
 
    <a href="#!" class="brand-logo">Project 1</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>


	<ul class="right hide-on-med-and-down">
		<li><a href="index.php">Home</a></li>
		<li><a href="tim-berners-lee.php">Tim Berners-Lee</a></li>
		<li><a href="grace-hopper.php">Grace Hopper</a></li>
		<li><a href="margaret-hamilton.php">Margaret Hamilton</a></li>
		<li><a href="colophon.php">Colophon</a></li>
	</ul>

	<ul class="side-nav" id="mobile-demo">
        <li><a href="index.php">Home</a></li>
		<li><a href="tim-berners-lee.php">Tim Berners-Lee</a></li>
		<li><a href="grace-hopper.php">Grace Hopper</a></li>
		<li><a href="margaret-hamilton.php">Margaret Hamilton</a></li>
		<li><a href="colophon.php">Colophon</a></li>
      </ul>
</div><!--.nav-wrapper-->
</nav>